//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos_movimientos
    {
        public string auto { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo { get; set; }
        public string documento { get; set; }
        public decimal importe { get; set; }
        public int signo { get; set; }
        public string estatus_conciliado { get; set; }
        public string auto_banco { get; set; }
        public string detalle { get; set; }
        public string numero_cuenta { get; set; }
        public string banco { get; set; }
        public string estatus_anulado { get; set; }
        public string entidad { get; set; }
        public string origen { get; set; }
        public string comprobante_egreso { get; set; }
        public string codigo_banco { get; set; }
        public System.DateTime fecha_cheque { get; set; }
        public string auto_asiento { get; set; }
        public string lote { get; set; }
        public string estatus_cierre_contable { get; set; }
    
        public virtual bancos bancos { get; set; }
    }
}
