//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos
    {
        public bancos()
        {
            this.contabilidad_banco = new HashSet<contabilidad_banco>();
            this.bancos_movimientos = new HashSet<bancos_movimientos>();
        }
    
        public string auto { get; set; }
        public string nombre { get; set; }
        public string tipo_cuenta { get; set; }
        public string numero_cuenta { get; set; }
        public int ultimo_numero_chq { get; set; }
        public string auto_codigo_plan { get; set; }
        public decimal saldo { get; set; }
        public decimal saldo_conciliado { get; set; }
        public string lugar { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string estatus { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public System.DateTime fecha_conciliacion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public decimal total_debitos { get; set; }
        public decimal total_creditos { get; set; }
        public string titular { get; set; }
        public string codigo { get; set; }
        public string naturaleza_cuenta { get; set; }
        public decimal idb { get; set; }
        public int numero_nota_debito { get; set; }
        public int numero_nota_credito { get; set; }
        public Nullable<int> idPlanCta { get; set; }
    
        public virtual ICollection<contabilidad_banco> contabilidad_banco { get; set; }
        public virtual ICollection<bancos_movimientos> bancos_movimientos { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta { get; set; }
    }
}
