//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos_movimientos_conceptos
    {
        public bancos_movimientos_conceptos()
        {
            this.contabilidad_banco_conceptos = new HashSet<contabilidad_banco_conceptos>();
        }
    
        public string auto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string clase { get; set; }
        public string auto_codigo_plan { get; set; }
        public Nullable<int> idPlanCtaPago { get; set; }
        public Nullable<int> idPlanCta { get; set; }
    
        public virtual ICollection<contabilidad_banco_conceptos> contabilidad_banco_conceptos { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta1 { get; set; }
    }
}
