//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_banco
    {
        public int id { get; set; }
        public string auto_banco { get; set; }
        public Nullable<int> idPlanCta_IGTF { get; set; }
        public Nullable<int> idPlanCta { get; set; }
    
        public virtual bancos bancos { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta1 { get; set; }
    }
}
