//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_historico
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string naturaleza { get; set; }
        public decimal saldoAperura { get; set; }
        public decimal saldoAnterior { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public string estado { get; set; }
        public Nullable<int> idPadre { get; set; }
        public int nivel { get; set; }
        public decimal debeAcumulado { get; set; }
        public decimal haberAcumulado { get; set; }
        public int mesHistorico { get; set; }
        public int anoHistorico { get; set; }
        public int idCta { get; set; }
    }
}
