//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_asiento_resumen
    {
        public int id { get; set; }
        public int idAsiento { get; set; }
        public int idPlanCta { get; set; }
        public decimal montoDebe { get; set; }
        public decimal montoHaber { get; set; }
        public string codigoCta { get; set; }
        public string descripcionCta { get; set; }
    
        public virtual contabilidad_asiento contabilidad_asiento { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta { get; set; }
    }
}
