//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_plancta
    {
        public contabilidad_plancta()
        {
            this.contabilidad_asiento_detalle = new HashSet<contabilidad_asiento_detalle>();
            this.contabilidad_asiento_resumen = new HashSet<contabilidad_asiento_resumen>();
            this.contabilidad_configuracion = new HashSet<contabilidad_configuracion>();
            this.contabilidad_plancta1 = new HashSet<contabilidad_plancta>();
            this.contabilidad_reglas_integracion_detalle = new HashSet<contabilidad_reglas_integracion_detalle>();
            this.contabilidad_banco = new HashSet<contabilidad_banco>();
            this.contabilidad_banco1 = new HashSet<contabilidad_banco>();
            this.bancos = new HashSet<bancos>();
            this.bancos_movimientos_conceptos = new HashSet<bancos_movimientos_conceptos>();
            this.bancos_movimientos_conceptos1 = new HashSet<bancos_movimientos_conceptos>();
            this.contabilidad_departamentos = new HashSet<contabilidad_departamentos>();
            this.contabilidad_departamentos1 = new HashSet<contabilidad_departamentos>();
            this.contabilidad_departamentos2 = new HashSet<contabilidad_departamentos>();
            this.contabilidad_departamentos3 = new HashSet<contabilidad_departamentos>();
            this.contabilidad_departamentos4 = new HashSet<contabilidad_departamentos>();
            this.contabilidad_empresa_medio = new HashSet<contabilidad_empresa_medio>();
        }
    
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string naturaleza { get; set; }
        public int id { get; set; }
        public decimal saldoApertura { get; set; }
        public decimal saldoAnterior { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public string estado { get; set; }
        public Nullable<int> idPadre { get; set; }
        public int nivel { get; set; }
        public decimal debeAcumulado { get; set; }
        public decimal haberAcumulado { get; set; }
        public decimal rsaldoApertura { get; set; }
        public decimal rsaldoAnterior { get; set; }
        public decimal rdebe { get; set; }
        public decimal rhaber { get; set; }
        public decimal rdebeAcumulado { get; set; }
        public decimal rhaberAcumulado { get; set; }
    
        public virtual ICollection<contabilidad_asiento_detalle> contabilidad_asiento_detalle { get; set; }
        public virtual ICollection<contabilidad_asiento_resumen> contabilidad_asiento_resumen { get; set; }
        public virtual ICollection<contabilidad_configuracion> contabilidad_configuracion { get; set; }
        public virtual ICollection<contabilidad_plancta> contabilidad_plancta1 { get; set; }
        public virtual contabilidad_plancta contabilidad_plancta2 { get; set; }
        public virtual ICollection<contabilidad_reglas_integracion_detalle> contabilidad_reglas_integracion_detalle { get; set; }
        public virtual ICollection<contabilidad_banco> contabilidad_banco { get; set; }
        public virtual ICollection<contabilidad_banco> contabilidad_banco1 { get; set; }
        public virtual ICollection<bancos> bancos { get; set; }
        public virtual ICollection<bancos_movimientos_conceptos> bancos_movimientos_conceptos { get; set; }
        public virtual ICollection<bancos_movimientos_conceptos> bancos_movimientos_conceptos1 { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos1 { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos2 { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos3 { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos4 { get; set; }
        public virtual ICollection<contabilidad_empresa_medio> contabilidad_empresa_medio { get; set; }
    }
}
