//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_tipo_documento
    {
        public contabilidad_tipo_documento()
        {
            this.contabilidad_asiento = new HashSet<contabilidad_asiento>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<contabilidad_asiento> contabilidad_asiento { get; set; }
    }
}
