//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_integraciones
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public string descripcion { get; set; }
        public int idAsiento { get; set; }
        public string estaAnulado { get; set; }
        public int idReglaIntegracion { get; set; }
    
        public virtual contabilidad_asiento contabilidad_asiento { get; set; }
        public virtual contabilidad_reglas_integracion contabilidad_reglas_integracion { get; set; }
    }
}
