//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_asiento_documento
    {
        public contabilidad_asiento_documento()
        {
            this.contabilidad_asiento_detalle = new HashSet<contabilidad_asiento_detalle>();
        }
    
        public int id { get; set; }
        public int idAsiento { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int signo { get; set; }
        public string incluir { get; set; }
    
        public virtual ICollection<contabilidad_asiento_detalle> contabilidad_asiento_detalle { get; set; }
    }
}
