//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad_asiento_docadm
    {
        public int id { get; set; }
        public int idAsiento { get; set; }
        public string autoDoc { get; set; }
        public int tipoDoc { get; set; }
    }
}
