//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_vendedor_comisiones_generadas
    {
        public int id { get; set; }
        public string auto_cxc { get; set; }
        public string auto_vendedor_comision { get; set; }
    
        public virtual cxc cxc { get; set; }
    }
}
