//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxp_documentos
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_documento { get; set; }
        public string documento { get; set; }
        public decimal importe { get; set; }
        public string operacion { get; set; }
        public string auto_cxp { get; set; }
        public string auto_cxp_pago { get; set; }
        public string auto_cxp_recibo { get; set; }
        public string numero_recibo { get; set; }
    }
}
