//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxp_recibos
    {
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string auto_usuario { get; set; }
        public decimal importe { get; set; }
        public string usuario { get; set; }
        public decimal monto_recibido { get; set; }
        public string auto_proveedor { get; set; }
        public string proveedor { get; set; }
        public string ci_rif { get; set; }
        public string codigo { get; set; }
        public string estatus_anulado { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public decimal anticipos { get; set; }
        public decimal cambio { get; set; }
        public string nota { get; set; }
        public string auto_cxp { get; set; }
    }
}
