//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dBEntities : DbContext
    {
        public dBEntities()
            : base("name=dBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<ventas_detalle> ventas_detalle { get; set; }
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<compras_retenciones> compras_retenciones { get; set; }
        public virtual DbSet<compras_detalle> compras_detalle { get; set; }
        public virtual DbSet<compras_retenciones_detalle> compras_retenciones_detalle { get; set; }
        public virtual DbSet<contabilidad_asiento> contabilidad_asiento { get; set; }
        public virtual DbSet<contabilidad_asiento_detalle> contabilidad_asiento_detalle { get; set; }
        public virtual DbSet<contabilidad_asiento_documento> contabilidad_asiento_documento { get; set; }
        public virtual DbSet<contabilidad_asiento_resumen> contabilidad_asiento_resumen { get; set; }
        public virtual DbSet<contabilidad_banco_conceptos> contabilidad_banco_conceptos { get; set; }
        public virtual DbSet<contabilidad_configuracion> contabilidad_configuracion { get; set; }
        public virtual DbSet<contabilidad_contadores> contabilidad_contadores { get; set; }
        public virtual DbSet<contabilidad_historico> contabilidad_historico { get; set; }
        public virtual DbSet<contabilidad_integraciones> contabilidad_integraciones { get; set; }
        public virtual DbSet<contabilidad_plancta> contabilidad_plancta { get; set; }
        public virtual DbSet<contabilidad_reglas_integracion> contabilidad_reglas_integracion { get; set; }
        public virtual DbSet<contabilidad_tipo_documento> contabilidad_tipo_documento { get; set; }
        public virtual DbSet<cxc_recibos> cxc_recibos { get; set; }
        public virtual DbSet<cxp> cxp { get; set; }
        public virtual DbSet<cxp_recibos> cxp_recibos { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<empresa_departamentos> empresa_departamentos { get; set; }
        public virtual DbSet<empresa_series_fiscales> empresa_series_fiscales { get; set; }
        public virtual DbSet<cxp_documentos> cxp_documentos { get; set; }
        public virtual DbSet<cxp_medio_pago> cxp_medio_pago { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_grupo> productos_grupo { get; set; }
        public virtual DbSet<productos_marca> productos_marca { get; set; }
        public virtual DbSet<productos_medida> productos_medida { get; set; }
        public virtual DbSet<productos_kardex> productos_kardex { get; set; }
        public virtual DbSet<productos_movimientos> productos_movimientos { get; set; }
        public virtual DbSet<productos_movimientos_detalle> productos_movimientos_detalle { get; set; }
        public virtual DbSet<productos_proveedor> productos_proveedor { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<empresa_cobradores> empresa_cobradores { get; set; }
        public virtual DbSet<empresa_medios> empresa_medios { get; set; }
        public virtual DbSet<bancos_movimientos_conceptos> bancos_movimientos_conceptos { get; set; }
        public virtual DbSet<ventas_retenciones> ventas_retenciones { get; set; }
        public virtual DbSet<cxc_vendedor_comisiones_generadas> cxc_vendedor_comisiones_generadas { get; set; }
        public virtual DbSet<cxc_retenciones_generadas> cxc_retenciones_generadas { get; set; }
        public virtual DbSet<contabilidad_reglas_integracion_detalle> contabilidad_reglas_integracion_detalle { get; set; }
        public virtual DbSet<cxc> cxc { get; set; }
        public virtual DbSet<ventas_retenciones_detalle> ventas_retenciones_detalle { get; set; }
        public virtual DbSet<productos_kardex_resumen> productos_kardex_resumen { get; set; }
        public virtual DbSet<productos_deposito> productos_deposito { get; set; }
        public virtual DbSet<cxc_medio_pago> cxc_medio_pago { get; set; }
        public virtual DbSet<contabilidad_banco> contabilidad_banco { get; set; }
        public virtual DbSet<contabilidad_deposito> contabilidad_deposito { get; set; }
        public virtual DbSet<empresa_depositos> empresa_depositos { get; set; }
        public virtual DbSet<bancos_movimientos> bancos_movimientos { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
        public virtual DbSet<sistema_contadores> sistema_contadores { get; set; }
        public virtual DbSet<contabilidad_asiento_docadm> contabilidad_asiento_docadm { get; set; }
        public virtual DbSet<contabilidad_departamentos> contabilidad_departamentos { get; set; }
        public virtual DbSet<contabilidad_empresa_medio> contabilidad_empresa_medio { get; set; }
        public virtual DbSet<contabilidad_periodo> contabilidad_periodo { get; set; }
        public virtual DbSet<compras> compras { get; set; }
    }
}
