//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_cobradores
    {
        public empresa_cobradores()
        {
            this.clientes = new HashSet<clientes>();
            this.cxc_recibos = new HashSet<cxc_recibos>();
        }
    
        public string auto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal comision { get; set; }
        public string contrato { get; set; }
    
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual ICollection<cxc_recibos> cxc_recibos { get; set; }
    }
}
