//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_departamentos
    {
        public empresa_departamentos()
        {
            this.compras_detalle = new HashSet<compras_detalle>();
            this.ventas_detalle = new HashSet<ventas_detalle>();
            this.productos = new HashSet<productos>();
            this.contabilidad_departamentos = new HashSet<contabilidad_departamentos>();
        }
    
        public string auto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal comision_g { get; set; }
        public decimal comision_1 { get; set; }
        public decimal comision_2 { get; set; }
        public decimal comision_3 { get; set; }
        public decimal comision_4 { get; set; }
    
        public virtual ICollection<compras_detalle> compras_detalle { get; set; }
        public virtual ICollection<ventas_detalle> ventas_detalle { get; set; }
        public virtual ICollection<productos> productos { get; set; }
        public virtual ICollection<contabilidad_departamentos> contabilidad_departamentos { get; set; }
    }
}
