//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_medios
    {
        public empresa_medios()
        {
            this.cxc_medio_pago = new HashSet<cxc_medio_pago>();
            this.contabilidad_empresa_medio = new HashSet<contabilidad_empresa_medio>();
        }
    
        public string auto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string estatus_cobro { get; set; }
        public string estatus_pago { get; set; }
    
        public virtual ICollection<cxc_medio_pago> cxc_medio_pago { get; set; }
        public virtual ICollection<contabilidad_empresa_medio> contabilidad_empresa_medio { get; set; }
    }
}
