//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_retenciones_detalle
    {
        public string auto_documento { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string ci_rif { get; set; }
        public string tipo { get; set; }
        public decimal exento { get; set; }
        public decimal @base { get; set; }
        public decimal impuesto { get; set; }
        public decimal total { get; set; }
        public decimal tasa_retencion { get; set; }
        public decimal retencion { get; set; }
        public string auto { get; set; }
        public System.DateTime fecha_retencion { get; set; }
        public string comprobante { get; set; }
        public string tipo_retencion { get; set; }
        public string aplica { get; set; }
        public string control { get; set; }
        public decimal tasa { get; set; }
        public int signo { get; set; }
    }
}
