//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_retenciones
    {
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string razon_social { get; set; }
        public string dir_fiscal { get; set; }
        public string ci_rif { get; set; }
        public string tipo { get; set; }
        public decimal exento { get; set; }
        public decimal @base { get; set; }
        public decimal impuesto { get; set; }
        public decimal total { get; set; }
        public decimal tasa_retencion { get; set; }
        public decimal retencion { get; set; }
        public string auto_cliente { get; set; }
        public System.DateTime fecha_relacion { get; set; }
        public string codigo_cliente { get; set; }
        public string ano_relacion { get; set; }
        public string mes_relacion { get; set; }
        public int renglones { get; set; }
        public string documento_nombre { get; set; }
        public string estatus_cierre_contable { get; set; }
    }
}
